fix syntax

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -21,10 +21,10 @@ jobs:
 
       - name: Verify no changes from goimports
         run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            git status    # These are the files that failed to pass the check.
-            exit 1
-          fi
+        if [ -n "$(git status --porcelain)" ]; then
+          git status    # These are the files that failed to pass the check.
+          exit 1
+        fi
 
   verify-gomod:
     runs-on: ubuntu-latest
@@ -41,7 +41,7 @@ jobs:
       run: find . -name go.mod -execdir go mod tidy \;
 
       - name: Verify no changes from goimports and go mod tidy.
-      run: |
+        run: |
         if [ -n "$(git status --porcelain)" ]; then
           git status    # These are the files that failed to pass the check.
           exit 1
